event_name = input("What is the name of your event? ")
host_name = input("What is the name of the host? ")
location = input("Where is the event taking place? ")
event_month = input("What month is the event? ")
event_day = int(input("What day is the event? "))

guest_count = int(input("How many guests are attending? "))
table_count = int(input("How many tables will be set up? "))
chair_count = int(input("How many chairs will be set up? "))
food_budget = float(input("What is the budget for food? "))
decor_budget = float(input("What is the budget for decorations? "))

start_time = input("What time does the event start? ")
end_time = input("What time does the event end? ")
first_activity = input("What is the first activity planned? ")
second_activity = input("What is the second activity planned? ")
closing_activity = input("What is the closing activity planned? ")

def event_profile(event_name, host_name, location, event_month, event_day, guest_count, table_count, chair_count, food_budget, decor_budget, start_time, end_time, first_activity, second_activity, closing_activity):
    print("Event Name: " + event_name)
    print("Host Name: " + host_name)
    print("Location: " + location)
    print("Event Date: " + event_month + " " + str(event_day))
    print("Number of Guests: " + str(guest_count))
    print("Number of Tables: " + str(table_count))
    print("Number of Chairs: " + str(chair_count))
    print("Food Budget: $" + str(food_budget))
    print("Decorations Budget: $" + str(decor_budget))
    print("Event Start Time: " + start_time)
    print("Event End Time: " + end_time)
    print("First Activity Planned: " + first_activity)
    print("Second Activity Planned: " + second_activity)
    print("Closing Activity Planned: " + closing_activity)

print(event_profile(event_name, host_name, location, event_month, event_day, guest_count, table_count, chair_count, food_budget, decor_budget, start_time, end_time, first_activity, second_activity, closing_activity))